version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
hooks:
  beforeinstall:
    - location: scripts/install_nginx.sh
      timeout: 300
      runas: root
   ApplicationStop:
    - location: scripts/start_nginx.sh
      timeout: 300
      runas: root

